N_PLAYERS = 10
START_ECONOMY = 100.0
MAX_DEFENSE = 1.0
MAX_MANUFACTURING = 1.0
DEFENSE_DECAY = 0.1
MANUFACTURING_DECAY = 0.1

ATTACK_FACTOR = 0.4
DEFENSE_LIMIT = 0.85 # Used in (0.85 - Defj)

ROAD_BUILD_COST_FACTOR = 0.2
TRADE_ROAD_MAX_FACTOR = 0.1
TRADE_ROAD_MIN_FACTOR = 0.05
TRADE_AIR_MAX_FACTOR = 0.1
TRADE_AIR_MIN_FACTOR = 0.1

INVEST_COST_FACTOR = 0.1
INVEST_GAIN = 1.0

BLACK_SWAN_START = 25
BLACK_SWAN_END = 75

SEED = 42
